# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2855ecef5997f640dbc7ab171e142de5465b25ed2a8e28a44ef2cf767f6b0e35c3a481c59490d70eb40d7843e84ccaa5e8418c0dec1116684860be02d5acedc5

test:
  secret_key_base: 34881312272b6ae0c290dd8610c62944def196b9bf535c139abc46bc11833ee1c5259fcdeb2146c7ad3d0dfbe9582af53c48de3ae2436d27b53704bf715a7fce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
